name: training-job

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -e .

      - name: Test running python
        run: |
          dvc pull
          python src/train.py
